### ISSUE TITLE
Curtailed lists

### ISSUE THREAD

**Issue by newtestleper** [tvillarete/ipod-classic-js#75]
My artists’ list stops at the end of the A’s, albums two albums into the C’s and the playlists aren’t all there either. Haven’t seen it mentioned?

**Comment by tvillarete** [comment]
Hey @newtestleper, can you confirm a few things for me?

1. Is this with Apple Music or Spotify?
2. How many artists do you have that start with "A"? 

Currently the list caps at 100 artists / albums, so that might be why you're seeing it cut off. I have a [ticket](https://github.com/tvillarete/ipod-classic-js/issues/34) to add pagination to the lists but haven't had much time to work on it. Let me know if this matches your issue. Thanks!

**Comment by Akira-25** [comment]
Hi, same here.
I could sign in and play music now but have the curtailed lists.
I only can see 25 Artists and 100 Albums. Both are shown in order from A to Z. The playlist shows songs that do not appear in the album list or artist list.

I'm using Apple Music Japan. I've tried to use it with Chrome and Safari and I had a same problem with both.

iPhone XS, iOS15.5, 170/256GB

**Comment by tvillarete** [comment]
FYI this should be fixed now. Going to close this ticket 👍

**Comment by Akira-25** [comment]
Thank you for your work. but I'm sorry I signed out and in and still have a same problem
